### ISSUE TITLE
Login Fails For Local CHT Instances With Invalid TLS Certificate

### ISSUE THREAD

**Issue by alexosugo** [medic/cht-user-management#107]
CHT instances installed via Docker have may have an optional TLS certificate installed to bypass the 'Your connection is not private' error that shows on the browser when you try to access it. When the CHT management tool is ran with the following env variables:

```
COOKIE_PRIVATE_KEY={your-cookie}
CONFIG_NAME=chis-ke
PORT=3555             
EXTERNAL_PORT=3555    # for docker
INTERFACE=127.0.0.1   
CHT_DEV_URL_PORT={your-local-ip}.local-ip.medicmobile.org 
CHT_DEV_HTTP=false   
```     

login fails with an `invalid certificate error`. See log below:

```
AxiosError: Hostname/IP does not match certificate's altnames: Host: 192.168.100.2.local-ip.medicmobile.org. is not in the cert's altnames: DNS:*.local-ip.medicmobile.org
    at Function.AxiosError.from (/Users/kombo/Medic/cht-user-management/node_modules/axios/dist/node/axios.cjs:837:14)
    at RedirectableRequest.handleRequestError (/Users/kombo/Medic/cht-user-management/node_modules/axios/dist/node/axios.cjs:3090:25)
    at RedirectableRequest.emit (node:events:513:28)
    at ClientRequest.eventHandlers.<computed> (/Users/kombo/Medic/cht-user-management/node_modules/follow-redirects/index.js:37:24)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_TLS_CERT_ALTNAME_INVALID',
  cert: {
    subject: [Object: null prototype] { CN: '*.local-ip.medicmobile.org' },
    issuer: [Object: null prototype] { C: 'US', O: "Let's Encrypt", CN: 'R3' },
    subjectaltname: 'DNS:*.local-ip.medicmobile.org',
    infoAccess: [Object: null prototype] {
      'OCSP - URI': [Array],
      'CA Issuers - URI': [Array]
    },
```

**Comment by derickl** [comment]
You can try ignoring TLS certificate validation.

e.g. `export NODE_TLS_REJECT_UNAUTHORIZED=0` before launching the user management tool?

**Comment by alexosugo** [comment]
Thanks @derickl. That and adding it appending it to the .env files work. I expect that some people have experienced a similar issue so this should help.

**Comment by derickl** [comment]
You probably don't need to do both. Does adding it to the env file (without exporting) work?

**Comment by alexosugo** [comment]
@derickl Not both. Either works. Even without exporting.

**Comment by mrjones-plip** [comment]
@alexosugo - I'm unable to reproduce this on current UMT docker images (2.1.6 as of this writing).  Can you try again and be sure to specify dev mode as a string, http as string (not a boolean) and the URL/port of local-ip instance?  Here's mine

```.env
NODE_ENV="dev"                      # set to "dev" to use CHT_DEV_URL_PORT below, leave empty for production
COOKIE_PRIVATE_KEY=64a29729-23d2-4cb7-908b-ab92222378cb               
WORKER_PRIVATE_KEY=64a29729-23d2-4cb7-908b-ab92222378c               
CONFIG_NAME=chis-ke  
INTERFACE=0.0.0.0 
CHT_DEV_HTTP='false'              # 'true' for http  'false' for https
CHT_DEV_URL_PORT=192-168-68-26.local-ip.medicmobile.org:10444 
```

I explicitly mention "string" above because I had some errors when i used an unquoted value which I suspected made `false` be evaluated as a truthy (not `null`) vs `'false'` which was a string  and parsed by the JS code finally as a boolean.   While your error (`'code: 'ERR_TLS_CERT_ALTNAME_INVALID',`) is different than mine (`The plain HTTP request was sent to HTTPS port`) - I'm curious if still reproduces for you!  

Be sure to test with latest images (`docker compose pull` in UMT directory)

**Comment by mrjones-plip** [comment]
Oh oh! I see the problem and was able to both reproduce the exact error, as well as find the work around.

To reproduce this error,  we can use the [Bad SSL test site](https://badssl.com/). To do this set your `CHT_DEV_URL_PORT=wrong.host.badssl.com` and you'll see the same `ERR_TLS_CERT_ALTNAME_INVALID` as above.  Now, set it to `192.168.68.26.local-ip.medicmobile.org:10444` and you'll see the same error.

The fix?  Us the correct URL!  Local IP has a structure of `NUM-NUM-NUM-NUM` with dashes (`-`) and NOT `NUM.NUM.NUM.NUM` with periods (`.`).  The pasted error above as URL:

```
AxiosError: Hostname/IP does not match certificate's altnames: Host: 192.168.100.2.local-ip.medicmobile.org. is not in the cert's altnames: DNS:*.local-ip.medicmobile.org
```

So the config is actually:

```
CHT_DEV_URL_PORT=192.168.100.2.local-ip.medicmobile.org
```

The fix is to use this address instead:

```
CHT_DEV_URL_PORT=192-168-100-2.local-ip.medicmobile.org
```

whew!! I was really struggling to reproduce this and was very happy when I did \o/
